pipeline {
    environment
    {
        REPO_PATH = "${WORKSPACE}/Unet2d_pytorch"
        script_path = "${WORKSPACE}/Unet2d_pytorch/Jenkins/start_file.sh"
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh ''' echo "TESSSST" '''
                sh ''' echo  ${REPO_PATH}'''
                sh '''
                    echo "JJJJJJJJJJ"
                '''
            }
        }
        stage("test PythonEnv") {
            steps{
                withPythonEnv('python3.8') {
                    sh 'pip install -r requirements.txt'
                    sh 'pytest test_model.py'
                }
            }
        }
    }
}