pipeline {
    environment
    {
        REPO_PATH = "${WORKSPACE}/Unet2d_pytorch"
        script_path = "${WORKSPACE}/Unet2d_pytorch/Jenkins/start_file.sh"
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh ''' echo "TESSSST" '''
                sh ''' echo  ${REPO_PATH}'''
                sh 'bash -e -c -x "chmod +x ' + script_path + '; . ' + script_path + '"'

                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
    }
}